//
//  StatementPresenter.swift
//  BankApp
//
//  Created by Ulisses Gomes on 03/04/20.
//  Copyright (c) 2020 Ulisses Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementPresentationLogic {
  func presentStatement(response: Statements.StatementList.ViewModel)
}

class StatementPresenter: StatementPresentationLogic {
   
  weak var viewController: StatementDisplayLogic?
  
  // MARK: Do something
  
  func presentStatement(response: Statements.StatementList.ViewModel) {
    viewController?.displayStatements(viewModel: response)
  }
}
