//
//  StatementWorker.swift
//  BankApp
//
//  Created by Ulisses Gomes on 03/04/20.
//  Copyright (c) 2020 Ulisses Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class StatementWorker {
    
    var statementStore: StatementStoreProtocol
    
    init(store: StatementStoreProtocol) {
        self.statementStore = store
    }
    
    func fetchStatements(userId: Int, completionHandler: @escaping (StatementResponse) -> ()) {
        statementStore.fetchStatements(userId, completionHandler: completionHandler)
    }
    
}

protocol StatementStoreProtocol {
    func fetchStatements(_ userId: Int, completionHandler: @escaping (StatementResponse) -> ())
}
