//
//  LoginPresenter.swift
//  BankApp
//
//  Created by Ulisses Gomes on 02/04/20.
//  Copyright (c) 2020 Ulisses Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func loginSucess(response: Login.UserAccount.Response)
    func loginError(error: Login.UserAccount.Error)
}

class LoginPresenter: LoginPresentationLogic {
    
  weak var viewController: LoginDisplayLogic?
  
  func loginSucess(response: Login.UserAccount.Response) {
    let model = Login.UserAccount.ViewModel(userId: response.userId, name: response.name, agency: response.agency, account: response.account, balance: response.balance)
      viewController?.loginSucess(user: model)
  }
  
  func loginError(error: Login.UserAccount.Error) {
       viewController?.loginError(error: error)
  }
  
  
}
