//
//  LoginModels.swift
//  BankApp
//
//  Created by Ulisses Gomes on 02/04/20.
//  Copyright (c) 2020 Ulisses Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {
    // MARK: Do login
    
    struct UserAccount {
        struct Request {
            var user: String
            var password: String
        }
        
        struct Error {
            var message: String
        }
        
        struct Response {
            var userId: Int
            var name: String
            var agency: String
            var account: String
            var balance: Float
        }
        
        struct ViewModel {
            var userId: Int
            var name: String
            var agency: String
            var account: String
            var balance: Float
        }
    }
    
}
